# Collection names
NODES = "nodes"
STARTUP_GRAPHS = "startup_graphs"
TASK_QUEUE = "task_queue"
PRODUCT_KNOWLEDGE_BASE = "product_knowledge_base"
DECISION_JOURNAL = "decision_journal"
DEAD_ENDS = "dead_ends"
BUILD_EVENTS = "build_events"
OBSERVE_EVENTS = "observe_events"
